# Build environment for development with => npm run start
# Run FROM CLI : docker build -f Dockerfile.dev -t express-sequelize-mysql .

FROM node:16-alpine

WORKDIR /app
COPY package.json .

ENV NODE_ENV=development
ENV PATH=/app/node_modules/.bin:$PATH

RUN yarn install
RUN yarn global add sequelize-cli nodemon

COPY . .

#RUN sequelize db:migrate

EXPOSE 3000

CMD npm start