version: '3.9'
services:
  express:
    container_name: express
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - /app
      - /app/node_modules
    environment:
      - NODE_ENV=production